//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

We will use https://aws-ia.github.io/taskcat/[tascat^] tool to package and upload the code artifacts

*Taskcat installation:*

1. Ensure you have http://pip.pypa.io/en/stable/installation/[pip] and https://docs.docker.com/get-started/get-docker/[Docker] installed on your system.
2. Install taskcat using pip: `pip install taskcat`. (for detailed instructions, visit https://aws-ia.github.io/taskcat/docs/INSTALLATION/[taskcat installation])
3. The https://github.com/awslabs/cfn-ecr-aws-soci-index-builder[cfn-ecr-aws-soci-index-builder] repository includes a `.taskcat.yml` configuration file that defines how taskcat should package and upload the resources.

*Once taskcat is installed, run taskcat upload from the git repository. This command will:*

* Read the configuration from `.taskcat.yml` file
* Package the lambda functions using the provided Dockerfile (this is why Docker is required)
* Create S3 buckets in all specified regions with the naming pattern `taskcat-cfn-ecr-aws-soci-index-builder-<account-hash>-<region>`
* Upload the CloudFormation template and Lambda packages to these buckets with the prefix `cfn-ecr-aws-soci-index-builder/`
* Make the CloudFormation template available at the URL pattern `https://<bucket-name>.s3.<region>.amazonaws.com/cfn-ecr-aws-soci-index-builder/templates/SociIndexBuilder.yml`

Sign in to the AWS CloudFormation console or call the CloudFormation CreateStack API using IAM credentials that have permissions to create, update, rollback, and delete a stack. Minimally, the IAM role must have permissions to create, modify, and delete stack resources. For more information, refer to https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/control-access-with-iam.html[Controlling access with Amazon Identity and Access Management].